export const LINKS = {
  login_api: '/login',
  login_server: '/api/auth/login',
  logout_api: '/logout',
  logout_server: '/api/auth/logout',
  token: '/api/auth/get-token',
  user_current_api: '/users/current',
  user_current_server: '/api/users/current',
  game: '/game',
  servers: '/servers',
  characters: '/characters',
  character_submit: '/character-submit',
  jx_server_server: '/api/jx2/server',
  jx_character_server: '/api/jx2/character',
  loren_character_server: '/api/loren/character',
  loren_server_server: '/api/loren/server',
  jx2: {
    gift_received: '/jx2-gift-received',
    birthday_gift: '/jx2-birthday-gift',
    claim_gift: '/jx2-claim-gift',
    claim_gift_server: '/api/jx2/claim-gift',
    blow_candle: '/blow-candle',
    blow_candle_server: '/api/jx2/blow-candle',
    blow_candle_info: '/blow-candle-info',
    ranking_blow_candle: '/ranking-blow-candle',
  },
  loren: {
    attack_boss: '/mu-attack-boss',
    attack_boss_server: '/api/loren/attack-boss',
    claim_gift: '/mu-claim-gift',
    claim_gift_server: '/api/loren/claim-gift',
    claim_gift_boss: '/mu-claim-gift-boss',
    claim_gift_boss_server: '/api/loren/claim-gift-boss',
    ranking_attack_boss: '/mu-ranking-attack-boss',
  },
}
